name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt update &&\
          sudo apt-get install build-essential automake libtool texinfo bison flex gawk \
          g++ git xxd curl wget gdisk gperf cpio bc screen texinfo unzip libgmp-dev \
          libmpfr-dev libmpc-dev libssl-dev libncurses-dev libglib2.0-dev libpixman-1-dev \
          libyaml-dev patchutils python3-pip zlib1g-dev device-tree-compiler dosfstools \
          mtools kpartx rsync
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd buildroot && git checkout --track origin/JH7110_VisionFive2_devel && cd ..
          cd u-boot && git checkout --track origin/JH7110_VisionFive2_devel && cd ..
          cd linux && git checkout --track origin/JH7110_VisionFive2_devel && cd ..
          cd opensbi && git checkout master && cd ..
          cd soft_3rdpart && git checkout JH7110_VisionFive2_devel && cd ..

          make -j$(nproc)
